### PR TITLE
Fix bug in `add_k_nn_edges` and add minor extension

### PR DESCRIPTION
**Pull request by anton-bushuiev**
#### Reference Issues/PRs

No related issues/PRs
#### What does this implement/fix? Explain your changes
This pull request fixes a bug in `add_k_nn_edges`. Currenly, `kneighbors_graph(X=dist_mat, ...)` leads to wrong results which may seem correct. According to [scikit-learn docs](https://scikit-learn.org/stable/modules/generated/sklearn.neighbors.kneighbors_graph.html), it does not support `X` to be a distance matrix.

Secondly, this PR adds `filter_distmat` to generalise self-loops filtering. It adds the functionality to filter inter- or intra- connections between nodes of a single or multiple chains. It may be useful to incorporate it into other functions to add edges. By running the following code you will get the visualized graphs.
```
for val in ['inter', 'intra']:
    edge_funcs = {
        'edge_construction_functions': [
            partial(add_k_nn_edges, k=2, long_interaction_threshold=0, exclude_edges=[val])
        ]
    }
    config = ProteinGraphConfig(**edge_funcs)
    g = construct_graph(config=config, pdb_code='10gs')
...
```
image
image

#### Pull Request Checklist

- [x] Added a note about the modification or contribution to the `./CHANGELOG.md` file (if applicable)
- [x] Added appropriate unit test functions in the `./graphein/tests/*` directories (if applicable)
- [ ] Modify documentation in the corresponding Jupyter Notebook under `./notebooks/` (if applicable)
- [x] Ran `python -m py.test tests/` and make sure that all unit tests pass (for small modifications, it might be sufficient to only run the specific test file, e.g., `python -m py.test tests/protein/test_graphs.py`)
- [x] Checked for style issues by running `black .` and `isort .`

### CODE REVIEW

**Comment by a-r-j** [comment]
Thanks for this @anton-bushuiev. Good spot!

LGTM! Would you be able to add a couple tests?

**Comment by anton-bushuiev** [comment]
Yeah, I'll add them tomorrow.

**Comment by anton-bushuiev** [comment]
Hi, @a-r-j ! I've added the tests. I had to fix a new bug introduced by the distance matrix filtering (see [this](https://github.com/scikit-learn/scikit-learn/pull/24834)) 😄.

**Comment by a-r-j** [comment]
Thanks for the contribution @anton-bushuiev!

**Pull request merged**
